exit 1 # Not intended to be run directly
##
## Lines beginning with ## are stripped when puconfig generates its script.
##
## This is the puconfig shell footer. It is inserted to the top of any script that
## puconfig writes. The rest of the script gets generated by puconfig, based upon
## the user config and commmand-line arguments
##

for arg in "$@"; do
    if [ "$arg" = "--help" ] || [ "$arg" = "-h" ]; then
        echo "This is a self-contained standalone puconfig script"
        echo ""
        echo "Usage: $0 options?"
        echo ""
        echo "When run without any options it will install config files embedded"
        echo "within according to the puconfig configuration."
        echo ""
        echo "Optionally, it accepts the following options:"
        echo "  -h,  --help     Output this help screen and exit"
        echo "       --version  Output version information and exit"
        echo "       --silent   Be silent, only output errors"
        exit 0
    elif [ "$arg" = "--version" ]; then
        echo "puconfig self-contained script generated by puconfig {{puconfig_version}}"
        exit 0
    elif [ "$arg" = "--silent" ]; then
        PUCONFIG_SILENT=1
    else
        echo "Unknown argument: $arg"
        echo "Run $0 --help for help"
        exit 1
    fi
done

# Install the configs
applyConfigs
